version: '3.8'

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    ports:
      - 3000:3000
    depends_on:
       - mongo

  api02:
    <<: *api
    hostname: api02
    ports:
      - 3001:3000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - 9999:9999

  mongo:
    image: mongo:7.0.3
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init-scripts/:/mongo-init-scripts/
      - ./mongo-init-scripts/mongo-import-script.sh:/docker-entrypoint-initdb.d/mongo-import-script.sh
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["mongod", "--quiet"]

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
