version: '3.8'

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
       - mongo
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    command: npm run start:debug

  # api02:
  #   <<: *api
  #   hostname: api02
  #   ports:
  #     - 3001:3000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - 9999:9999


  mongo:
      image: bitnami/mongodb:5.0
      ports:
        - 27017:27017
      environment:
        MONGODB_REPLICA_SET_MODE: primary
        ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - ./mongo-init-scripts:/docker-entrypoint-initdb.d



networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
